"""Novas colunas na tabela Viagem

Revision ID: 03fbe6d6f567
Revises: 3a0f93fffb06
Create Date: 2025-10-10 17:08:14.545271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fbe6d6f567'
down_revision: Union[str, Sequence[str], None] = '3a0f93fffb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viagem', 'status_viagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('status_viagem', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
