"""Novas colunas na tabela Viagem

Revision ID: 633c86dbe01c
Revises: 03fbe6d6f567
Create Date: 2025-10-10 17:08:29.476192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633c86dbe01c'
down_revision: Union[str, Sequence[str], None] = '03fbe6d6f567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('status_viagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viagem', 'status_viagem')
    # ### end Alembic commands ###
