"""Novas colunas na tabela Viagem

Revision ID: 934bb36eb73e
Revises: 633c86dbe01c
Create Date: 2025-10-10 18:03:30.966828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934bb36eb73e'
down_revision: Union[str, Sequence[str], None] = '633c86dbe01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viagem', 'status_viagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('status_viagem', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
