"""Novas colunas na tabela Viagem

Revision ID: f493da3054bb
Revises: 934bb36eb73e
Create Date: 2025-10-10 18:04:12.865830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f493da3054bb'
down_revision: Union[str, Sequence[str], None] = '934bb36eb73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('status_viagem', sa.String(), nullable=True))
    op.drop_column('viagem', 'data_viagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('data_viagem', sa.DATE(), nullable=True))
    op.drop_column('viagem', 'status_viagem')
    # ### end Alembic commands ###
